# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 11:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quick_format', '0002_quick_rxncon_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quick',
            name='rxncon_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='rxncon_system_quicktele', to='rule_based.Rule_based_from_rxnconsys'),
        ),
    ]
