# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_format', '0003_quick_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
