# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0006_graph_from_quick'),
        ('quick_format', '0004_quick_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick',
            name='reg_graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graphs.Graph_from_File'),
        ),
    ]
