# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule_based', '0001_initial'),
        ('quick_format', '0007_quick_boolean_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick',
            name='rule_based_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_based_quick', to='rule_based.Rule_based_from_rxnconsys'),
        ),
    ]
