# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0009_remove_graph_from_file_option1'),
        ('quick_format', '0008_quick_rule_based_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick',
            name='sRea_graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species reaction_graph_quick+', to='graphs.Graph_from_File'),
        ),
    ]
