# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-22 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bool_from_rxnconsys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('smoothing', models.CharField(choices=[('no_smoothing', 'no_smoothing'), ('smooth_production_sources', 'smooth_production_sources')], default='smooth_production_sources', help_text='Smoothing strategy.', max_length=25)),
                ('knockout', models.CharField(choices=[('no_knockout', 'no_knockout'), ('knockout_neutral_states', 'knockout_neutral_states'), ('knockout_all_states', 'knockout_all_states')], default='no_knockout', help_text='Generate knockouts.', max_length=23)),
                ('overexpr', models.CharField(choices=[('no_overexpression', 'no_overexpression'), ('overexpress_neutral_states', 'overexpress_neutral_states'), ('overexpress_all_states', 'overexpress_all_states')], default='no_overexpression', help_text='Generate overexpressions.', max_length=26)),
                ('k_plus', models.CharField(choices=[('strict', 'strict'), ('ignore', 'ignore')], default='strict', help_text='Strategy for handling k+ contingencies.', max_length=6)),
                ('k_minus', models.CharField(choices=[('strict', 'strict'), ('ignore', 'ignore')], default='strict', help_text='Strategy for handling k- contingencies.', max_length=6)),
                ('model_path', models.FileField(null=True, upload_to='')),
                ('symbol_path', models.FileField(null=True, upload_to='')),
                ('init_path', models.FileField(null=True, upload_to='')),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
    ]
