# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boolean_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bool_from_rxnconsys',
            name='k_minus',
            field=models.CharField(choices=[('strict', 'strict'), ('ignore', 'ignore')], default='strict', help_text='Strategy for handling k- contingencies.', max_length=6),
        ),
        migrations.AddField(
            model_name='bool_from_rxnconsys',
            name='k_plus',
            field=models.CharField(choices=[('strict', 'strict'), ('ignore', 'ignore')], default='strict', help_text='Strategy for handling k+ contingencies.', max_length=6),
        ),
        migrations.AddField(
            model_name='bool_from_rxnconsys',
            name='knockout',
            field=models.CharField(choices=[('no_knockout', 'no_knockout'), ('knockout_neutral_states', 'knockout_neutral_states'), ('knockout_all_states', 'knockout_all_states')], default='no_knockout', help_text='Generate knockouts.', max_length=23),
        ),
        migrations.AddField(
            model_name='bool_from_rxnconsys',
            name='overexpr',
            field=models.CharField(choices=[('no_overexpression', 'no_overexpression'), ('overexpress_neutral_states', 'overexpress_neutral_states'), ('overexpress_all_states', 'overexpress_all_states')], default='no_overexpression', help_text='Generate overexpressions.', max_length=26),
        ),
        migrations.AlterField(
            model_name='bool_from_rxnconsys',
            name='smoothing',
            field=models.CharField(choices=[('no_smoothing', 'no_smoothing'), ('smooth_production_sources', 'smooth_production_sources')], default='no_smoothing', help_text='Smoothing strategy.', max_length=25),
        ),
    ]
