# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 17:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rule_based', '0001_initial'),
        ('fileTree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='rxncon_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='rxncon_system_file', to='rule_based.Rule_based_from_rxnconsys'),
        ),
    ]
