# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 12:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fileTree', '0002_file_rxncon_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='rxncon_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='rxncon_system_file', to='rxncon_system.Rxncon_system'),
        ),
    ]
