# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileTree', '0003_file_loaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
