# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20160614_1314'),
        ('fileTree', '0004_auto_20160523_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='reg_graph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graphs.Graph_from_File'),
        ),
    ]
