# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileTree', '0005_file_reg_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='reg_graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graphs.Graph_from_File'),
        ),
    ]
