# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import graphs.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileTree', '0004_auto_20160523_1630'),
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_from_file',
            name='connected_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fileTree.File'),
        ),
        migrations.AddField(
            model_name='graph_from_file',
            name='graph_file',
            field=models.FileField(null=True, upload_to=graphs.models.upload_location),
        ),
        migrations.AddField(
            model_name='graph_from_file',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
