# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20160524_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph_from_file',
            name='graph_file',
            field=models.FilePathField(null=True),
        ),
    ]
