# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20160614_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph_from_file',
            name='connected_system',
        ),
        migrations.AlterField(
            model_name='graph_from_file',
            name='graph_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
