# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20160614_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph_from_file',
            name='graph_string',
            field=models.TextField(null=True),
        ),
    ]
