# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_graph_from_file_graph_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph_from_Quick',
            fields=[
                ('graph_from_file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='graphs.Graph_from_File')),
            ],
            bases=('graphs.graph_from_file',),
        ),
    ]
