# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0007_graph_from_file_option1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph_from_file',
            name='option1',
            field=models.NullBooleanField(default=True),
        ),
    ]
