# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0008_auto_20170313_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph_from_file',
            name='option1',
        ),
    ]
