# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rxncon_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rxncon_system',
            name='project_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
