# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rxncon_system', '0003_auto_20170520_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='rxncon_system',
            name='project_type',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
